services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: turborepo_postgres_website
    shm_size: 128mb
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: turborepo
      POSTGRES_PASSWORD: 123456789
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
  redis_data:
    driver: local