# syntax=docker/dockerfile:1

FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat git
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

FROM base AS deps
ENV NODE_ENV=development
RUN corepack enable && corepack prepare pnpm@10.20.0 --activate
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY apps ./apps
RUN git init && pnpm install --frozen-lockfile

FROM deps AS build
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NODE_ENV=production
COPY apps/www ./apps/www
WORKDIR /app/apps/www
RUN pnpm install --frozen-lockfile
RUN pnpm build

FROM base AS runner
ENV NODE_ENV=production
RUN corepack enable && corepack prepare pnpm@10.20.0 --activate
WORKDIR /app/apps/www
ENV PORT=3000
EXPOSE 3000
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=deps /app/apps/www/node_modules /app/apps/www/node_modules
COPY --from=build /app/apps/www/.next ./.next
COPY --from=build /app/apps/www/public ./public
COPY apps/www/package.json ./package.json
CMD ["pnpm", "exec", "next", "start"]


