import type { NameTheme } from "@/lib/vault-tools/name-themes";

/** Star Trek: Uhura runs comms, Worf runs security, Memory Alpha is the archive. */
export const STARTREK_THEME: NameTheme = {
  key: "startrek",
  domains: ["starfleet", "federation", "sector001", "utopia", "alphaquad"],
  roles: {
    dc: ["kirk", "picard", "sisko", "janeway", "archer"],
    dns: ["majel", "daystrom", "lcars", "computer"],
    dhcp: ["obrien", "rand", "quartermaster", "yeoman"],
    exchange: ["uhura", "hoshi", "subspace", "comrelay"],
    sql: ["data", "daystrom", "lcars", "memoryalpha"],
    file: ["memoryalpha", "cargobay", "jefferies", "archive"],
    backup: ["b4", "memorybeta", "phoenix", "genesis"],
    monitoring: ["spock", "sensorarray", "tuvok", "longrange"],
    firewall: ["worf", "odo", "deflector", "shields", "neutralzone"],
    proxy: ["transporter", "obrien", "relaystation", "wormhole"],
    web: ["viewscreen", "bridge", "lcars", "promenade"],
    hypervisor: ["enterprise", "voyager", "defiant", "discovery", "galaxy"],
    nas: ["cargobay", "jefferies", "replimat", "shuttlebay"],
    print: ["replicator", "synthesizer", "fabricator"],
    vpn: ["wormhole", "subspace", "transwarp", "corridor"],
    dev: ["laforge", "scotty", "torres", "warpcore", "engineering"],
    test: ["holodeck", "kobayashi", "tribble", "borgcube"],
    client: [
      "chekov",
      "sulu",
      "riker",
      "crusher",
      "bashir",
      "dax",
      "kim",
      "paris",
      "neelix",
      "seven",
      "tpol",
      "mayweather",
      "mccoy",
      "troi",
      "guinan",
      "quark",
      "kira",
      "tk421",
    ],
    admin: ["readyroom", "bridge", "admiralty", "command", "sisko"],
  },
  pool: [
    "kirk",
    "spock",
    "mccoy",
    "scotty",
    "uhura",
    "sulu",
    "chekov",
    "rand",
    "chapel",
    "pike",
    "number one",
    "sarek",
    "amanda",
    "tpring",
    "khan",
    "gorn",
    "trelane",
    "picard",
    "riker",
    "data",
    "laforge",
    "worf",
    "troi",
    "crusher",
    "wesley",
    "guinan",
    "obrien",
    "ro",
    "barclay",
    "yar",
    "pulaski",
    "lore",
    "b4",
    "lal",
    "q",
    "borgqueen",
    "sisko",
    "kira",
    "odo",
    "bashir",
    "dax",
    "jadzia",
    "ezri",
    "quark",
    "rom",
    "nog",
    "garak",
    "dukat",
    "weyoun",
    "martok",
    "gowron",
    "damar",
    "leeta",
    "morn",
    "vic",
    "janeway",
    "chakotay",
    "tuvok",
    "torres",
    "paris",
    "kim",
    "neelix",
    "kes",
    "seven",
    "doctor",
    "icheb",
    "naomi",
    "sevenofnine",
    "borgcube",
    "archer",
    "tpol",
    "trip",
    "reed",
    "hoshi",
    "mayweather",
    "phlox",
    "porthos",
    "burnham",
    "saru",
    "tilly",
    "stamets",
    "culber",
    "georgiou",
    "lorca",
    "pike",
    "enterprise",
    "voyager",
    "defiant",
    "discovery",
    "excelsior",
    "reliant",
    "grissom",
    "stargazer",
    "prometheus",
    "equinox",
    "intrepid",
    "sovereign",
    "galaxy",
    "nebula",
    "akira",
    "miranda",
    "constitution",
    "constellation",
    "ambassador",
    "steamrunner",
    "runabout",
    "delta flyer",
    "shuttlepod",
    "danube",
    "sarajevo",
    "yamato",
    "hood",
    "vulcan",
    "andoria",
    "tellar",
    "betazed",
    "bajor",
    "cardassia",
    "qonos",
    "romulus",
    "remus",
    "ferenginar",
    "risa",
    "trill",
    "kronos",
    "earth",
    "mars",
    "utopia",
    "starbase",
    "ds9",
    "terok nor",
    "regula",
    "genesis",
    "nimbus",
    "ceti",
    "wolf359",
    "memoryalpha",
    "memorybeta",
    "daystrom",
    "vulcanhigh",
    "shipyard",
    "spacedock",
    "warpcore",
    "nacelle",
    "deflector",
    "shields",
    "phaser",
    "torpedo",
    "tricorder",
    "communicator",
    "transporter",
    "replicator",
    "holodeck",
    "holosuite",
    "lcars",
    "sensorarray",
    "impulse",
    "warpdrive",
    "transwarp",
    "slipstream",
    "dilithium",
    "antimatter",
    "plasmaconduit",
    "jefferies",
    "cargobay",
    "shuttlebay",
    "sickbay",
    "readyroom",
    "bridge",
    "viewscreen",
    "promenade",
    "replimat",
    "brig",
    "messhall",
    "borg",
    "romulan",
    "klingon",
    "vulcanid",
    "ferengi",
    "cardassian",
    "bajoran",
    "dominion",
    "jemhadar",
    "vorta",
    "founder",
    "changeling",
    "breen",
    "tholian",
    "gorncap",
    "andorian",
    "orion",
    "trillsym",
    "talaxian",
    "ocampa",
    "hirogen",
    "kazon",
    "species8472",
    "tribble",
    "horta",
    "crystalline",
    "doomsday",
    "nomad",
    "vger",
    "kobayashi",
    "primedirective",
    "generalorder",
    "neutralzone",
    "temporalprime",
    "subspace",
    "wormhole",
    "nexus",
    "mirroruniverse",
    "terranempire",
    "section31",
    "maquis",
    "obsidianorder",
    "tal shiar",
    "starfleetacademy",
    "commandcodes",
    "phoenix",
    "cochrane",
    "zefram",
    "firstcontact",
    "warpfive",
    "nx01",
    "ncc1701",
    "majel",
    "computer",
    "moriarty",
    "vic fontaine",
    "flint",
    "soong",
    "juliana",
  ],
};

/** Star Wars: Kamino clones, the shield gate blocks, the Jedi archive answers lookups. */
export const STARWARS_THEME: NameTheme = {
  key: "starwars",
  domains: ["republic", "coruscant", "empire", "outerrim", "jedi", "rebellion"],
  roles: {
    dc: ["yoda", "windu", "vader", "thrawn", "coruscant"],
    dns: ["jocasta", "archives", "holocron", "beacon"],
    dhcp: ["r2d2", "astromech", "hangar", "quartermaster"],
    exchange: ["c3po", "holonet", "transmitter", "protocol"],
    sql: ["holocron", "archives", "jocasta", "datacron"],
    file: ["datavault", "cargohold", "kessel", "spicevault"],
    backup: ["kamino", "bacta", "cloningvat", "carbonite"],
    monitoring: ["viperprobe", "probedroid", "sentinel", "comscan"],
    firewall: ["shieldgate", "blockade", "ionshield", "deflector", "vader"],
    proxy: ["hyperlane", "relaystation", "holonet", "transponder"],
    web: ["holonet", "senate", "cantina", "beacon"],
    hypervisor: ["executor", "venator", "deathstar", "hangarbay", "stardestroyer"],
    nas: ["sandcrawler", "kessel", "cargohold", "spicevault"],
    print: ["geonosis", "foundry", "fabricator", "droidworks"],
    vpn: ["hyperspace", "kesselrun", "smugglerun", "corridor"],
    dev: ["kamino", "geonosis", "droidworks", "workshop"],
    test: ["trashcompactor", "sarlacc", "carbonite", "trainingremote"],
    client: [
      "luke",
      "leia",
      "han",
      "chewie",
      "lando",
      "rey",
      "finn",
      "poe",
      "ahsoka",
      "obiwan",
      "mando",
      "grogu",
      "jango",
      "cody",
      "rex",
      "wedge",
      "tk421",
      "ct7567",
    ],
    admin: ["council", "senate", "moff", "grandadmiral", "tarkin", "palpatine"],
  },
  pool: [
    "luke",
    "leia",
    "han",
    "chewbacca",
    "chewie",
    "vader",
    "obiwan",
    "yoda",
    "palpatine",
    "r2d2",
    "c3po",
    "lando",
    "wedge",
    "ackbar",
    "mothma",
    "tarkin",
    "boba",
    "jango",
    "greedo",
    "jabba",
    "bib",
    "salacious",
    "sarlacc",
    "ewok",
    "wicket",
    "nien",
    "snap",
    "quigon",
    "anakin",
    "padme",
    "amidala",
    "jarjar",
    "windu",
    "kenobi",
    "dooku",
    "maul",
    "grievous",
    "ahsoka",
    "rex",
    "cody",
    "fives",
    "echo",
    "hunter",
    "wrecker",
    "tech",
    "crosshair",
    "omega",
    "bail",
    "breha",
    "shmi",
    "watto",
    "sebulba",
    "aayla",
    "plokoon",
    "kitfisto",
    "shaakti",
    "luminara",
    "barriss",
    "eeth",
    "adigallia",
    "sifodyas",
    "rey",
    "finn",
    "poe",
    "kylo",
    "bb8",
    "hux",
    "phasma",
    "snoke",
    "maz",
    "rose",
    "holdo",
    "dameron",
    "zorii",
    "jannah",
    "babu",
    "dio",
    "beaumont",
    "mando",
    "djarin",
    "grogu",
    "cara",
    "greef",
    "bokatan",
    "fennec",
    "cobb",
    "migs",
    "moff",
    "gideon",
    "thrawn",
    "ezra",
    "sabine",
    "hera",
    "zeb",
    "kanan",
    "chopper",
    "cassian",
    "jyn",
    "krennic",
    "chirrut",
    "baze",
    "bodhi",
    "k2so",
    "galen",
    "saw",
    "coruscant",
    "tatooine",
    "alderaan",
    "hoth",
    "dagobah",
    "bespin",
    "endor",
    "naboo",
    "kamino",
    "geonosis",
    "mustafar",
    "kashyyyk",
    "utapau",
    "felucia",
    "mygeeto",
    "jakku",
    "takodana",
    "crait",
    "exegol",
    "ahchto",
    "canto",
    "scarif",
    "jedha",
    "eadu",
    "yavin",
    "dantooine",
    "corellia",
    "kessel",
    "mandalore",
    "nevarro",
    "sorgan",
    "tython",
    "ilum",
    "starkiller",
    "lothal",
    "malachor",
    "dathomir",
    "ryloth",
    "sullust",
    "millennium",
    "falcon",
    "xwing",
    "ywing",
    "awing",
    "bwing",
    "tiefighter",
    "tieinterceptor",
    "stardestroyer",
    "executor",
    "venator",
    "deathstar",
    "tantive",
    "ghost",
    "razorcrest",
    "slave1",
    "nebulon",
    "moncal",
    "raddus",
    "supremacy",
    "finalizer",
    "eclipse",
    "atat",
    "atst",
    "atte",
    "aatr",
    "speederbike",
    "landspeeder",
    "sandcrawler",
    "podracer",
    "lightsaber",
    "kyber",
    "holocron",
    "datacron",
    "beskar",
    "carbonite",
    "bacta",
    "hyperdrive",
    "hyperspace",
    "hyperlane",
    "kesselrun",
    "holonet",
    "comscan",
    "ionshield",
    "shieldgate",
    "deflector",
    "tractorbeam",
    "blaster",
    "thermaldetonator",
    "vibroblade",
    "protondrive",
    "astromech",
    "probedroid",
    "viperprobe",
    "sentinel",
    "droideka",
    "battledroid",
    "b1",
    "b2",
    "magnaguard",
    "ig88",
    "ig11",
    "hk47",
    "bd1",
    "l337",
    "jedi",
    "sith",
    "padawan",
    "younglings",
    "council",
    "temple",
    "archives",
    "jocasta",
    "force",
    "darkside",
    "lightside",
    "midichlorian",
    "holochess",
    "senate",
    "republic",
    "empire",
    "rebellion",
    "alliance",
    "firstorder",
    "resistance",
    "separatist",
    "trade",
    "hutt",
    "cartel",
    "bountyguild",
    "spice",
    "smugglerun",
    "cantina",
    "mos eisley",
    "stormtrooper",
    "clonetrooper",
    "deathtrooper",
    "shoretrooper",
    "scouttrooper",
    "tk421",
    "ct7567",
    "ct5555",
    "cc2224",
    "royalguard",
    "inquisitor",
    "purge",
  ],
};

/** Dune: a ghola is a restored copy, the Holtzman field shields, a Heighliner carries worlds. */
export const DUNE_THEME: NameTheme = {
  key: "dune",
  domains: ["arrakis", "imperium", "landsraad", "caladan", "sietch", "dune"],
  roles: {
    dc: ["atreides", "leto", "muaddib", "shaddam", "corrino"],
    dns: ["thufir", "mentat", "oracle", "seer"],
    dhcp: ["windtrap", "watermaster", "cistern", "qanat"],
    exchange: ["courier", "herald", "distrans", "guildcomm"],
    sql: ["othermemory", "mentat", "archives", "bibliocode"],
    file: ["sietch", "spicevault", "tabr", "cavern"],
    backup: ["ghola", "axolotl", "othermemory", "watercache"],
    monitoring: ["truthsayer", "seer", "spotter", "thumper"],
    firewall: ["holtzman", "shieldwall", "sardaukar", "fedaykin"],
    proxy: ["heighliner", "navigator", "spacingguild", "foldspace"],
    web: ["landsraad", "herald", "crier", "assembly"],
    hypervisor: ["heighliner", "caladan", "arrakis", "kaitain"],
    nas: ["sietchtabr", "spicevault", "cistern", "watercache"],
    print: ["ixian", "ix", "fabricator", "suk"],
    vpn: ["foldspace", "holtzmandrive", "desertroute", "sietchpath"],
    dev: ["ix", "tleilax", "workshop", "ixianprobe"],
    test: ["gomjabbar", "tleilax", "sandworm", "agony", "crysknife"],
    client: [
      "chani",
      "duncan",
      "gurney",
      "jessica",
      "stilgar",
      "alia",
      "irulan",
      "feyd",
      "liet",
      "kynes",
      "hawat",
      "halleck",
      "harah",
      "naib",
      "fremen",
      "shadout",
      "otheym",
      "korba",
    ],
    admin: ["reverendmother", "sayyadina", "landsraad", "padishah", "siridar"],
  },
  pool: [
    "leto",
    "paul",
    "muaddib",
    "usul",
    "jessica",
    "alia",
    "chani",
    "duncan",
    "gurney",
    "thufir",
    "yueh",
    "stilgar",
    "liet",
    "kynes",
    "harah",
    "otheym",
    "korba",
    "jamis",
    "shadout",
    "mapes",
    "irulan",
    "shaddam",
    "feyd",
    "rabban",
    "harkonnen",
    "piter",
    "vladimir",
    "fenring",
    "margot",
    "hasimir",
    "ghanima",
    "leto2",
    "farad",
    "moneo",
    "duncanidaho",
    "siona",
    "hwi",
    "malky",
    "nayla",
    "miles",
    "teg",
    "odrade",
    "lucilla",
    "murbella",
    "sheeana",
    "scytale",
    "waff",
    "bijaz",
    "edric",
    "gaius",
    "helen",
    "mohiam",
    "atreides",
    "corrino",
    "vernius",
    "richese",
    "ecaz",
    "moritani",
    "ginaz",
    "fenrings",
    "arrakis",
    "dune",
    "caladan",
    "giediprime",
    "kaitain",
    "salusa",
    "ix",
    "tleilax",
    "wallach",
    "chapterhouse",
    "rakis",
    "gammu",
    "buzzell",
    "lampadas",
    "junction",
    "sietch",
    "sietchtabr",
    "tabr",
    "cavern",
    "shieldwall",
    "polarsink",
    "arrakeen",
    "carthag",
    "tuono",
    "onslaught",
    "habbanya",
    "cielago",
    "funeralplain",
    "bledlands",
    "sandworm",
    "shaihulud",
    "makermaker",
    "sandtrout",
    "spice",
    "melange",
    "wormsign",
    "thumper",
    "maker hooks",
    "crysknife",
    "stillsuit",
    "stilltent",
    "windtrap",
    "qanat",
    "cistern",
    "watercache",
    "watermaster",
    "deathstill",
    "fremkit",
    "paracompass",
    "holtzman",
    "shield",
    "lasgun",
    "maula",
    "gomjabbar",
    "hunterseeker",
    "shigawire",
    "distrans",
    "ornithopter",
    "thopter",
    "carryall",
    "harvester",
    "spotter",
    "groundcar",
    "heighliner",
    "foldspace",
    "navigator",
    "spacingguild",
    "highliner",
    "frigate",
    "mentat",
    "truthsayer",
    "reverendmother",
    "sayyadina",
    "benegesserit",
    "benetleilax",
    "suk",
    "swordmaster",
    "sardaukar",
    "fedaykin",
    "fremen",
    "naib",
    "sietchcouncil",
    "landsraad",
    "padishah",
    "siridar",
    "faufreluches",
    "kanly",
    "amtal",
    "tahaddi",
    "ghola",
    "axolotl",
    "othermemory",
    "agony",
    "waterOfLife",
    "spiceagony",
    "prescience",
    "goldenpath",
    "kwisatz",
    "haderach",
    "muadhib",
    "lisanalgaib",
    "mahdi",
    "jihad",
    "missionaria",
    "protectiva",
    "azhar",
    "orangecatholic",
    "bibliocode",
    "manual",
    "ixian",
    "richesian",
    "guildbank",
    "solari",
    "chops",
    "spicetrade",
    "melangeharvest",
    "desertpower",
    "sandrider",
    "makerkeeper",
    "sietchtau",
    "kitab",
    "burseg",
    "bashar",
    "caid",
    "levenbrech",
    "umma",
    "wali",
    "zensunni",
    "zensufi",
    "mihna",
    "hajj",
    "courier",
    "herald",
    "crier",
    "assembly",
    "archives",
    "seer",
    "oracle",
    "fabricator",
  ],
};

/** Cyberpunk: ICE is the firewall, the Oracle resolves, replicants are copies. */
export const CYBERPUNK_THEME: NameTheme = {
  key: "cyberpunk",
  domains: ["nightcity", "neonet", "mainframe", "arasaka", "zion", "gridlock"],
  roles: {
    dc: ["wintermute", "morpheus", "mainframe", "tyrell", "core"],
    dns: ["oracle", "lookup", "nameless", "resolver"],
    dhcp: ["operator", "dispatcher", "broker", "handler"],
    exchange: ["courier", "uplink", "tank", "dropbox"],
    sql: ["datavault", "ledger", "memex", "blackbox"],
    file: ["coldstore", "silo", "datahaven", "lockbox"],
    backup: ["replicant", "snapshot", "phantom", "coldstorage"],
    monitoring: ["panopticon", "sentinel", "deckard", "watchdog"],
    firewall: ["blackice", "icewall", "netwatch", "gibson", "chokepoint"],
    proxy: ["jackpoint", "gateway", "trapdoor", "relay"],
    web: ["neonsign", "storefront", "kiosk", "holoboard"],
    hypervisor: ["matrix", "mainframe", "hivecore", "simstim"],
    nas: ["offshore", "datahaven", "silo", "coldstore"],
    print: ["fabricator", "printshop", "extruder", "chrome"],
    vpn: ["darklink", "ghostwire", "tunnel", "blacklink"],
    dev: ["netrunner", "kernel", "solder", "workshop"],
    test: ["sandbox", "dejavu", "glitch", "honeypot", "testbed"],
    client: [
      "neo",
      "trinity",
      "cypher",
      "switch",
      "mouse",
      "case",
      "molly",
      "armitage",
      "johnny",
      "roy",
      "rachael",
      "motoko",
      "batou",
      "ronin",
      "choom",
      "edgerunner",
      "solo",
      "fixer",
    ],
    admin: ["architect", "overseer", "sysop", "rootkit", "godmode"],
  },
  pool: [
    "neo",
    "trinity",
    "morpheus",
    "cypher",
    "switch",
    "apoc",
    "tank",
    "dozer",
    "mouse",
    "niobe",
    "ghost",
    "seraph",
    "oracle",
    "architect",
    "merovingian",
    "persephone",
    "sentinel",
    "agent",
    "smith",
    "brown",
    "jones",
    "zion",
    "nebuchadnezzar",
    "logos",
    "case",
    "molly",
    "armitage",
    "wintermute",
    "neuromancer",
    "riviera",
    "finn",
    "maelcum",
    "dixie",
    "flatline",
    "straylight",
    "villa",
    "tessier",
    "ashpool",
    "3jane",
    "hosaka",
    "deckard",
    "roy",
    "batty",
    "rachael",
    "pris",
    "zhora",
    "leon",
    "gaff",
    "tyrell",
    "sebastian",
    "bryant",
    "replicant",
    "voight",
    "kampff",
    "spinner",
    "offworld",
    "motoko",
    "batou",
    "togusa",
    "aramaki",
    "ishikawa",
    "saito",
    "paz",
    "borma",
    "tachikoma",
    "puppetmaster",
    "laughingman",
    "section9",
    "cyberbrain",
    "ghostline",
    "johnny",
    "vlink",
    "jane",
    "spider",
    "pharmakom",
    "yakuza",
    "loteks",
    "jones",
    "arasaka",
    "militech",
    "kangtao",
    "zetatech",
    "biotechnica",
    "trauma",
    "netwatch",
    "maelstrom",
    "valentinos",
    "tygerclaws",
    "voodooboys",
    "animals",
    "sixth street",
    "nightcity",
    "watson",
    "pacifica",
    "heywood",
    "westbrook",
    "santo",
    "badlands",
    "chibacity",
    "sprawl",
    "bama",
    "freeside",
    "cyberspace",
    "matrix",
    "grid",
    "gridlock",
    "mainframe",
    "megatower",
    "arcology",
    "combatzone",
    "afterlife",
    "lizzies",
    "netrunner",
    "solo",
    "fixer",
    "rockerboy",
    "techie",
    "medtech",
    "corpo",
    "nomad",
    "media",
    "cop",
    "edgerunner",
    "choom",
    "ronin",
    "samurai",
    "console cowboy",
    "blackice",
    "icewall",
    "icebreaker",
    "daemon",
    "kernel",
    "rootkit",
    "backdoor",
    "trapdoor",
    "honeypot",
    "wormhole",
    "logicbomb",
    "cutter",
    "spike",
    "shard",
    "jackpoint",
    "deck",
    "cyberdeck",
    "simstim",
    "braindance",
    "neurallink",
    "wetware",
    "chrome",
    "cyberarm",
    "kiroshi",
    "mantisblade",
    "gorillaarm",
    "sandevistan",
    "berserk",
    "kerenzikov",
    "monowire",
    "projectile",
    "trauma team",
    "ripperdoc",
    "panopticon",
    "watchdog",
    "sentry",
    "drone",
    "aerostat",
    "sky eye",
    "streetcam",
    "flatline",
    "burnout",
    "cyberpsycho",
    "eddies",
    "scrip",
    "creddie",
    "datashard",
    "datahaven",
    "offshore",
    "coldstore",
    "coldstorage",
    "silo",
    "lockbox",
    "blackbox",
    "ledger",
    "memex",
    "datavault",
    "snapshot",
    "phantom",
    "mirrorshade",
    "ghostwire",
    "darklink",
    "blacklink",
    "tunnel",
    "uplink",
    "downlink",
    "relay",
    "gateway",
    "neonsign",
    "holoboard",
    "storefront",
    "kiosk",
    "vendbot",
    "fabricator",
    "extruder",
    "printshop",
    "dejavu",
    "glitch",
    "sandbox",
    "testbed",
    "overseer",
    "sysop",
    "godmode",
  ],
};

/** Cosmos: the magnetosphere shields, Polaris is fixed, the Oort cloud is deep storage. */
export const COSMOS_THEME: NameTheme = {
  key: "cosmos",
  domains: ["cosmos", "heliosphere", "milkyway", "orbit", "lagrange", "deepspace"],
  roles: {
    dc: ["polaris", "sol", "vega", "sirius", "canopus"],
    dns: ["pulsar", "beacon", "lighthouse", "quasar"],
    dhcp: ["houston", "groundcontrol", "launchpad", "dispatcher"],
    exchange: ["telstar", "voyager", "pioneer", "relaysat"],
    sql: ["messier", "gaia", "catalog", "hipparcos"],
    file: ["deepstore", "archive", "vault", "kuiper"],
    backup: ["ark", "phoenix", "lagrange", "oortcloud"],
    monitoring: ["hubble", "webb", "keck", "arecibo", "observatory"],
    firewall: ["magnetosphere", "heliopause", "vanallen", "shieldbelt"],
    proxy: ["goldstone", "relay", "canberra", "madrid"],
    web: ["horizon", "aurora", "corona", "beacon"],
    hypervisor: ["nebula", "galaxy", "solaris", "orion"],
    nas: ["oortcloud", "kuiper", "asteroidbelt", "silo"],
    print: ["starforge", "foundry", "nova", "crucible"],
    vpn: ["wormhole", "einsteinrosen", "hyperspace", "tunnel"],
    dev: ["canaveral", "baikonur", "skunkworks", "labmodule"],
    test: ["vandenberg", "testrange", "windtunnel", "sandbox"],
    client: [
      "luna",
      "titan",
      "europa",
      "callisto",
      "io",
      "phobos",
      "deimos",
      "rhea",
      "dione",
      "iapetus",
      "triton",
      "charon",
      "ceres",
      "vesta",
      "pallas",
      "juno",
      "mimas",
      "tethys",
    ],
    admin: ["houston", "missioncontrol", "capcom", "groundcontrol", "flightdirector"],
  },
  pool: [
    "sol",
    "mercury",
    "venus",
    "terra",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "ceres",
    "vesta",
    "pallas",
    "juno",
    "hygiea",
    "eros",
    "psyche",
    "bennu",
    "ryugu",
    "itokawa",
    "chariklo",
    "chiron",
    "sedna",
    "quaoar",
    "orcus",
    "makemake",
    "haumea",
    "eris",
    "dysnomia",
    "gonggong",
    "arrokoth",
    "halley",
    "encke",
    "hale bopp",
    "luna",
    "phobos",
    "deimos",
    "io",
    "europa",
    "ganymede",
    "callisto",
    "amalthea",
    "himalia",
    "titan",
    "rhea",
    "iapetus",
    "dione",
    "tethys",
    "enceladus",
    "mimas",
    "hyperion",
    "phoebe",
    "janus",
    "epimetheus",
    "miranda",
    "ariel",
    "umbriel",
    "titania",
    "oberon",
    "triton",
    "nereid",
    "proteus",
    "charon",
    "nix",
    "hydra",
    "kerberos",
    "styx",
    "polaris",
    "sirius",
    "canopus",
    "arcturus",
    "vega",
    "capella",
    "rigel",
    "procyon",
    "achernar",
    "betelgeuse",
    "hadar",
    "altair",
    "acrux",
    "aldebaran",
    "antares",
    "spica",
    "pollux",
    "fomalhaut",
    "deneb",
    "mimosa",
    "regulus",
    "adhara",
    "castor",
    "shaula",
    "bellatrix",
    "elnath",
    "miaplacidus",
    "alnilam",
    "alnair",
    "alnitak",
    "mirfak",
    "dubhe",
    "wezen",
    "kaus",
    "alkaid",
    "sargas",
    "avior",
    "menkalinan",
    "atria",
    "alhena",
    "peacock",
    "alsephina",
    "mirzam",
    "alphard",
    "hamal",
    "algieba",
    "diphda",
    "nunki",
    "mizar",
    "alcor",
    "algol",
    "izar",
    "rasalhague",
    "kochab",
    "denebola",
    "andromeda",
    "orion",
    "cassiopeia",
    "cepheus",
    "draco",
    "lyra",
    "aquila",
    "cygnus",
    "perseus",
    "pegasus",
    "auriga",
    "bootes",
    "carina",
    "centaurus",
    "corvus",
    "crux",
    "hercules",
    "hydraconst",
    "leo",
    "lupus",
    "monoceros",
    "ophiuchus",
    "phoenix",
    "sagittarius",
    "scorpius",
    "taurus",
    "ursa",
    "vela",
    "virgo",
    "lyraconst",
    "aquarius",
    "nebula",
    "pleiades",
    "hyades",
    "praesepe",
    "trifid",
    "lagoon",
    "eagle",
    "helix",
    "ring",
    "crab",
    "veil",
    "horsehead",
    "carinaneb",
    "tarantula",
    "rosette",
    "dumbbell",
    "milkyway",
    "andromedagal",
    "triangulum",
    "sombrero",
    "whirlpool",
    "pinwheel",
    "magellanic",
    "centaurusa",
    "messier",
    "ngc",
    "quasar",
    "pulsar",
    "magnetar",
    "blazar",
    "supernova",
    "kilonova",
    "nova",
    "singularity",
    "eventhorizon",
    "accretion",
    "protostar",
    "whitedwarf",
    "redgiant",
    "brown dwarf",
    "neutronstar",
    "apollo",
    "gemini",
    "artemis",
    "voyager",
    "pioneer",
    "cassini",
    "galileo",
    "juno probe",
    "newhorizons",
    "curiosity",
    "perseverance",
    "opportunity",
    "spirit",
    "sojourner",
    "ingenuity",
    "viking",
    "magellan",
    "ulysses",
    "rosetta",
    "philae",
    "dawn",
    "parker",
    "hubble",
    "webb",
    "kepler",
    "tess",
    "spitzer",
    "chandra",
    "gaia",
    "hipparcos",
    "planck",
    "herschel",
    "swift",
    "fermi",
    "keck",
    "arecibo",
    "vlt",
    "alma",
    "vla",
    "canaveral",
    "baikonur",
    "kourou",
    "vandenberg",
    "wallops",
    "tanegashima",
    "houston",
    "goldstone",
    "canberra",
    "madrid",
    "missioncontrol",
    "capcom",
    "groundcontrol",
    "lagrange",
    "heliopause",
    "heliosphere",
    "magnetosphere",
    "vanallen",
    "termination",
    "oortcloud",
    "kuiper",
    "asteroidbelt",
    "trojan",
    "roche",
    "perihelion",
    "aphelion",
    "apogee",
    "perigee",
    "aurora",
    "corona",
    "chromosphere",
    "photosphere",
    "solarwind",
    "sunspot",
    "flare",
    "eclipse",
    "transit",
    "parallax",
    "redshift",
    "blueshift",
    "starforge",
    "crucible",
    "horizon",
    "zenith",
    "nadir",
    "azimuth",
    "meridian",
    "orbit",
    "deepspace",
    "hyperspace",
    "wormhole",
    "einsteinrosen",
    "solaris",
    "galaxy",
    "cosmos",
  ],
};
